public class SOSLQueries {
    /*
find {Tech} in all fields returning Account(Name)
find {Finance} in all fields  returning Lead(Id,Industry),Contact(Id,Account.Industry)
3class
find {Smartphone} in all fields  returning Product2 (Id, Name, Description)
find {ram4*} in all fields  returning Case(Id, CaseNumber, AccountId, Account.Name)
NO Knowledgearticles
find {John Smith} in all fields  returning Event(Id, StartDateTime, EndDateTime, Account.Name)
8pass
find {New*} in all fields  returning Case(Id),Account(Id),Contact(Id)
find {@zenith.com} in all fields  returning Lead(Id,Email)
NO Knowledgearticles
*/

}